# Generated by Django 5.2 on 2025-04-10 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SysstockApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sucursal',
            new_name='Branch',
        ),
        migrations.RenameModel(
            old_name='Producto',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Proveedor',
            new_name='Provider',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
    ]
