# Generated by Django 5.2 on 2025-04-29 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SysstockApp', '0003_alter_branch_name_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'permissions': [('manage_branch', 'Can manage branches')]},
        ),
    ]
