# Generated by Django 5.2 on 2025-04-29 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SysstockApp', '0004_alter_branch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={},
        ),
    ]
