# Generated by Django 5.2 on 2025-10-07 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysstockApp', '0006_category_remove_product_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='SysstockApp.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='SysstockApp.branch'),
            preserve_default=False,
        ),
    ]
