# Generated by Django 5.2 on 2025-10-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysstockApp', '0006_category_remove_product_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
