# Generated by Django 5.2 on 2025-10-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysstockApp', '0009_alter_category_options_category_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
