# Generated by Django 5.2 on 2025-10-27 03:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysstockApp', '0010_branch_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='costo_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['nombre'], name='SysstockApp_nombre_a8d423_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sucursal'], name='SysstockApp_sucursa_feac4e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['categoria'], name='SysstockApp_categor_308564_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['producto', 'sucursal', 'tipo'], name='SysstockApp_product_7a2a34_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['creado_en'], name='SysstockApp_creado__9ac2c2_idx'),
        ),
    ]
