# Generated by Django 5.2 on 2025-10-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysstockApp', '0011_alter_stockmovement_options_stockmovement_costo_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
