# Generated by Django 5.2 on 2025-11-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysstockApp', '0012_product_sku_product_stock_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
