# Generated by Django 5.2 on 2025-11-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysstockApp', '0013_category_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='tipo',
            field=models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso'), ('SALE', 'Venta')], max_length=8),
        ),
    ]
