# Generated by Django 5.2 on 2025-11-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysstockApp', '0014_alter_stockmovement_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='tipo',
            field=models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso')], max_length=3),
        ),
    ]
