# Generated by Django 5.2 on 2025-04-22 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SysstockApp', '0003_alter_branch_name_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('limMerchant', 'Limitado')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SysstockApp.branch')),
            ],
        ),
    ]
