# Generated by Django 5.2 on 2025-04-29 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountAdmin', '0001_initial'),
    ]

    operations = [
    ]
