# Generated by Django 5.2 on 2025-04-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountAdmin', '0002_auto_20250429_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sucursal',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
