# Generated by Django 5.2 on 2025-04-29 23:41

from django.db import migrations, models
from django.db import connection


def add_sucursal_if_not_exists(apps, schema_editor):
    """Add sucursal column only if it doesn't exist"""
    with connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'AccountAdmin_user'
            AND COLUMN_NAME = 'sucursal'
        """)
        exists = cursor.fetchone()[0] > 0
        
        if not exists:
            # Add the column
            cursor.execute("""
                ALTER TABLE AccountAdmin_user
                ADD COLUMN sucursal VARCHAR(100) DEFAULT '' NOT NULL
            """)


def reverse_add_sucursal(apps, schema_editor):
    """Remove sucursal column if it exists"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'AccountAdmin_user'
            AND COLUMN_NAME = 'sucursal'
        """)
        exists = cursor.fetchone()[0] > 0
        
        if exists:
            cursor.execute("ALTER TABLE AccountAdmin_user DROP COLUMN sucursal")


class Migration(migrations.Migration):

    dependencies = [
        ('AccountAdmin', '0002_auto_20250429_2032'),
    ]

    operations = [
        migrations.RunPython(add_sucursal_if_not_exists, reverse_add_sucursal),
    ]
