# Generated by Django 5.2 on 2025-04-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountAdmin', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('limMerchant', 'Limitado')], default='limMerchant', max_length=20),
        ),
    ]
