# Generated by Django 5.2 on 2025-04-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountAdmin', '0003_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sucursal',
            field=models.CharField(default='', max_length=100),
        ),
    ]
