# Generated by Django 5.2 on 2025-10-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountAdmin', '0003_auto_20250429_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sucursal',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
