# Generated by Django 5.2 on 2025-10-21 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountAdmin', '0004_add_sucursal_to_user'),
        ('SysstockApp', '0006_category_remove_product_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('limMerchant', 'Limmerchant')], default='limMerchant', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='SysstockApp.branch'),
        ),
    ]
