# Generated by Django 5.2 on 2025-10-22 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountAdmin', '0005_alter_user_email_alter_user_rol_alter_user_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sucursal',
        ),
    ]
