# Generated by Django 5.2 on 2025-10-22 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountAdmin', '0006_remove_user_sucursal'),
        ('SysstockApp', '0007_add_branch_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='SysstockApp.branch'),
        ),
    ]
