# Generated by Django 5.2 on 2025-10-22 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountAdmin', '0007_user_sucursal'),
        ('SysstockApp', '0007_add_branch_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='SysstockApp.branch'),
        ),
    ]
