# Generated by Django 5.2 on 2025-10-22 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountAdmin', '0008_alter_user_sucursal'),
        ('SysstockApp', '0008_alter_branch_options_branch_owner_alter_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('limMerchant', 'Limmerchant')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='SysstockApp.branch'),
        ),
    ]
